export class Country {

  /**
   *name of the country
   *
   * @type {string}
   * @memberof Country
   */
  public Name: string;
  /**
   *ISO code of the country
   *
   * @type {string}
   * @memberof Country
   */
  public ISO: string;

  /**
   *Creates an instance of Country.
   * @param {string} name
   * @param {string} iso
   * @memberof Country
   */
  public constructor(name: string, iso: string) {
    if (name.length > 20) { // Shorten for better display
      this.Name = name.substr(0, 20) + '...';
    } else {
      this.Name = name;
    }
    this.ISO = iso;
  }
}

/**
 *All known country names and their ISO values
 *
 * @export
 * @class CountryList
 */
export class CountryList {
  static ListOfCountries: Array<Country> = [
    new Country('Afghanistan', 'AFG'),
    new Country('Åland Islands', 'ALA'),
    new Country('Albania', 'ALB'),
    new Country('Algeria', 'DZA'),
    new Country('American Samoa', 'ASM'),
    new Country('Andorra', 'AND'),
    new Country('Angola', 'AGO'),
    new Country('Anguilla', 'AIA'),
    new Country('Antarctica', 'ATA'),
    new Country('Antigua and Barbuda', 'ATG'),
    new Country('Argentina', 'ARG'),
    new Country('Armenia', 'ARM'),
    new Country('Aruba', 'ABW'),
    new Country('Australia', 'AUS'),
    new Country('Austria', 'AUT'),
    new Country('Azerbaijan', 'AZE'),
    new Country('Bahamas', 'BHS'),
    new Country('Bahrain', 'BHR'),
    new Country('Bangladesh', 'BGD'),
    new Country('Barbados', 'BRB'),
    new Country('Belarus', 'BLR'),
    new Country('Belgium', 'BEL'),
    new Country('Belize', 'BLZ'),
    new Country('Benin', 'BEN'),
    new Country('Bermuda', 'BMU'),
    new Country('Bhutan', 'BTN'),
    new Country('Bolivia (Plurinational State of)', 'BOL'),
    new Country('Bonaire, Sint Eustatius and Saba', 'BES'),
    new Country('Bosnia and Herzegovina', 'BIH'),
    new Country('Botswana', 'BWA'),
    new Country('Bouvet Island', 'BVT'),
    new Country('Brazil', 'BRA'),
    new Country('British Indian Ocean Territory', 'IOT'),
    new Country('Brunei Darussalam', 'BRN'),
    new Country('Bulgaria', 'BGR'),
    new Country('Burkina Faso', 'BFA'),
    new Country('Burundi', 'BDI'),
    new Country('Cabo Verde', 'CPV'),
    new Country('Cambodia', 'KHM'),
    new Country('Cameroon', 'CMR'),
    new Country('Canada', 'CAN'),
    new Country('Cayman Islands', 'CYM'),
    new Country('Central African Republic', 'CAF'),
    new Country('Chad', 'TCD'),
    new Country('Chile', 'CHL'),
    new Country('China', 'CHN'),
    new Country('Christmas Island', 'CXR'),
    new Country('Cocos (Keeling) Islands', 'CCK'),
    new Country('Colombia', 'COL'),
    new Country('Comoros', 'COM'),
    new Country('Congo', 'COG'),
    new Country('Congo (Democratic Republic of the)', 'COD'),
    new Country('Cook Islands', 'COK'),
    new Country('Costa Rica', 'CRI'),
    new Country('Côte dIvoire', 'CIV'),
    new Country('Croatia', 'HRV'),
    new Country('Cuba', 'CUB'),
    new Country('Curaçao', 'CUW'),
    new Country('Cyprus', 'CYP'),
    new Country('Czechia', 'CZE'),
    new Country('Denmark', 'DNK'),
    new Country('Djibouti', 'DJI'),
    new Country('Dominica', 'DMA'),
    new Country('Dominican Republic', 'DOM'),
    new Country('Ecuador', 'ECU'),
    new Country('Egypt', 'EGY'),
    new Country('El Salvador', 'SLV'),
    new Country('Equatorial Guinea', 'GNQ'),
    new Country('Eritrea', 'ERI'),
    new Country('Estonia', 'EST'),
    new Country('Eswatini', 'SWZ'),
    new Country('Ethiopia', 'ETH'),
    new Country('Falkland Islands (Malvinas)', 'FLK'),
    new Country('Faroe Islands', 'FRO'),
    new Country('Fiji', 'FJI'),
    new Country('Finland', 'FIN'),
    new Country('France', 'FRA'),
    new Country('French Guiana', 'GUF'),
    new Country('French Polynesia', 'PYF'),
    new Country('French Southern Territories', 'ATF'),
    new Country('Gabon', 'GAB'),
    new Country('Gambia', 'GMB'),
    new Country('Georgia', 'GEO'),
    new Country('Germany', 'DEU'),
    new Country('Ghana', 'GHA'),
    new Country('Gibraltar', 'GIB'),
    new Country('Greece', 'GRC'),
    new Country('Greenland', 'GRL'),
    new Country('Grenada', 'GRD'),
    new Country('Guadeloupe', 'GLP'),
    new Country('Guam', 'GUM'),
    new Country('Guatemala', 'GTM'),
    new Country('Guernsey', 'GGY'),
    new Country('Guinea', 'GIN'),
    new Country('Guinea-Bissau', 'GNB'),
    new Country('Guyana', 'GUY'),
    new Country('Haiti', 'HTI'),
    new Country('Heard Island and McDonald Islands', 'HMD'),
    new Country('Holy See', 'VAT'),
    new Country('Honduras', 'HND'),
    new Country('Hong Kong', 'HKG'),
    new Country('Hungary', 'HUN'),
    new Country('Iceland', 'ISL'),
    new Country('India', 'IND'),
    new Country('Indonesia', 'IDN'),
    new Country('Iran (Islamic Republic of)', 'IRN'),
    new Country('Iraq', 'IRQ'),
    new Country('Ireland', 'IRL'),
    new Country('Isle of Man', 'IMN'),
    new Country('Israel', 'ISR'),
    new Country('Italy', 'ITA'),
    new Country('Jamaica', 'JAM'),
    new Country('Japan', 'JPN'),
    new Country('Jersey', 'JEY'),
    new Country('Jordan', 'JOR'),
    new Country('Kazakhstan', 'KAZ'),
    new Country('Kenya', 'KEN'),
    new Country('Kiribati', 'KIR'),
    new Country('Korea (Democratic Peoples Republic of)', 'PRK'),
    new Country('Korea (Republic of)', 'KOR'),
    new Country('Kuwait', 'KWT'),
    new Country('Kyrgyzstan', 'KGZ'),
    new Country('Lao Peoples Democratic Republic', 'LAO'),
    new Country('Latvia', 'LVA'),
    new Country('Lebanon', 'LBN'),
    new Country('Lesotho', 'LSO'),
    new Country('Liberia', 'LBR'),
    new Country('Libya', 'LBY'),
    new Country('Liechtenstein', 'LIE'),
    new Country('Lithuania', 'LTU'),
    new Country('Luxembourg', 'LUX'),
    new Country('Macao', 'MAC'),
    new Country('Macedonia (the former Yugoslav Republic of)', 'MKD'),
    new Country('Madagascar', 'MDG'),
    new Country('Malawi', 'MWI'),
    new Country('Malaysia', 'MYS'),
    new Country('Maldives', 'MDV'),
    new Country('Mali', 'MLI'),
    new Country('Malta', 'MLT'),
    new Country('Marshall Islands', 'MHL'),
    new Country('Martinique', 'MTQ'),
    new Country('Mauritania', 'MRT'),
    new Country('Mauritius', 'MUS'),
    new Country('Mayotte', 'MYT'),
    new Country('Mexico', 'MEX'),
    new Country('Micronesia (Federated States of)', 'FSM'),
    new Country('Moldova (Republic of)', 'MDA'),
    new Country('Monaco', 'MCO'),
    new Country('Mongolia', 'MNG'),
    new Country('Montenegro', 'MNE'),
    new Country('Montserrat', 'MSR'),
    new Country('Morocco', 'MAR'),
    new Country('Mozambique', 'MOZ'),
    new Country('Myanmar', 'MMR'),
    new Country('Namibia', 'NAM'),
    new Country('Nauru', 'NRU'),
    new Country('Nepal', 'NPL'),
    new Country('Netherlands', 'NLD'),
    new Country('New Caledonia', 'NCL'),
    new Country('New Zealand', 'NZL'),
    new Country('Nicaragua', 'NIC'),
    new Country('Niger', 'NER'),
    new Country('Nigeria', 'NGA'),
    new Country('Niue', 'NIU'),
    new Country('Norfolk Island', 'NFK'),
    new Country('Northern Mariana Islands', 'MNP'),
    new Country('Norway', 'NOR'),
    new Country('Oman', 'OMN'),
    new Country('Pakistan', 'PAK'),
    new Country('Palau', 'PLW'),
    new Country('Palestine, State of', 'PSE'),
    new Country('Panama', 'PAN'),
    new Country('Papua New Guinea', 'PNG'),
    new Country('Paraguay', 'PRY'),
    new Country('Peru', 'PER'),
    new Country('Philippines', 'PHL'),
    new Country('Pitcairn', 'PCN'),
    new Country('Poland', 'POL'),
    new Country('Portugal', 'PRT'),
    new Country('Puerto Rico', 'PRI'),
    new Country('Qatar', 'QAT'),
    new Country('Réunion', 'REU'),
    new Country('Romania', 'ROU'),
    new Country('Russian Federation', 'RUS'),
    new Country('Rwanda', 'RWA'),
    new Country('Saint Barthélemy', 'BLM'),
    new Country('Saint Helena, Ascension and Tristan da Cunha', 'SHN'),
    new Country('Saint Kitts and Nevis', 'KNA'),
    new Country('Saint Lucia', 'LCA'),
    new Country('Saint Martin (French part)', 'MAF'),
    new Country('Saint Pierre and Miquelon', 'SPM'),
    new Country('Saint Vincent and the Grenadines', 'VCT'),
    new Country('Samoa', 'WSM'),
    new Country('San Marino', 'SMR'),
    new Country('Sao Tome and Principe', 'STP'),
    new Country('Saudi Arabia', 'SAU'),
    new Country('Senegal', 'SEN'),
    new Country('Serbia', 'SRB'),
    new Country('Seychelles', 'SYC'),
    new Country('Sierra Leone', 'SLE'),
    new Country('Singapore', 'SGP'),
    new Country('Sint Maarten (Dutch part)', 'SXM'),
    new Country('Slovakia', 'SVK'),
    new Country('Slovenia', 'SVN'),
    new Country('Solomon Islands', 'SLB'),
    new Country('Somalia', 'SOM'),
    new Country('South Africa', 'ZAF'),
    new Country('South Georgia and the South Sandwich Islands', 'SGS'),
    new Country('South Sudan', 'SSD'),
    new Country('Spain', 'ESP'),
    new Country('Sri Lanka', 'LKA'),
    new Country('Sudan', 'SDN'),
    new Country('Suriname', 'SUR'),
    new Country('Svalbard and Jan Mayen', 'SJM'),
    new Country('Sweden', 'SWE'),
    new Country('Switzerland', 'CHE'),
    new Country('Syrian Arab Republic', 'SYR'),
    new Country('Taiwan, Province of China[a]', 'TWN'),
    new Country('Tajikistan', 'TJK'),
    new Country('Tanzania, United Republic of', 'TZA'),
    new Country('Thailand', 'THA'),
    new Country('Timor-Leste', 'TLS'),
    new Country('Togo', 'TGO'),
    new Country('Tokelau', 'TKL'),
    new Country('Tonga', 'TON'),
    new Country('Trinidad and Tobago', 'TTO'),
    new Country('Tunisia', 'TUN'),
    new Country('Turkey', 'TUR'),
    new Country('Turkmenistan', 'TKM'),
    new Country('Turks and Caicos Islands', 'TCA'),
    new Country('Tuvalu', 'TUV'),
    new Country('Uganda', 'UGA'),
    new Country('Ukraine', 'UKR'),
    new Country('United Arab Emirates', 'ARE'),
    new Country('United Kingdom of Great Britain and Northern Ireland', 'GBR'),
    new Country('United States of America', 'USA'),
    new Country('United States Minor Outlying Islands', 'UMI'),
    new Country('Uruguay', 'URY'),
    new Country('Uzbekistan', 'UZB'),
    new Country('Vanuatu', 'VUT'),
    new Country('Venezuela (Bolivarian Republic of)', 'VEN'),
    new Country('Viet Nam', 'VNM'),
    new Country('Virgin Islands (British)', 'VGB'),
    new Country('Virgin Islands (U.S.)', 'VIR'),
    new Country('Wallis and Futuna', 'WLF'),
    new Country('Western Sahara', 'ESH'),
    new Country('Yemen', 'YEM'),
    new Country('Zambia', 'ZMB'),
    new Country('Zimbabwe', 'ZWE')
  ];
}
