/**
 *A Race that either took part in the past or will take place in the furture
 *
 * @export
 * @class Race
 */
export class Race {
    /**
     *Unique Identifier,
     *Generated by entity framework
     *
     * @type {number}
     * @memberof Race
     */
    public Id: number;
    /**
     *The date and time the race takes place, in ms since unix epoch
     *
     * @type {number}
     * @memberof Race
     */
    public Date: number;
    /**
     *Link to the announcement of the race
     *Has to be a valid URL  (RFC1738)
     *
     * @type {string}
     * @memberof Race
     */
    public Link: string;
    /**
     *The Title of the race,
     *required
     *
     * @type {string}
     * @memberof Race
     */
    public Title: string;
    /**
     *Wether this race has been started / completed in the past
     *
     * @type {boolean}
     * @memberof Race
     */
    public Done: boolean;
}
